# Generated by Django 3.2.4 on 2021-07-17 12:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', multiselectfield.db.fields.MultiSelectField(choices=[('CAR', 'CAR'), ('Wildlife', 'Wildlife'), ('Potrait', 'Potrait')], max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
